export default [
  {
    key:1,
    title:'首页',
    icon:'home',
    path:'/admin/index'
  },
  {
    key:2,
    title:'管理页管理',
    icon:'Dashboard',
    path:'/admin/administrator',
    children:[
      {
      key:2-1,
      title:'成员信息页',
      path:'/admin/info'
      },
      {
        key:2-2,
        title:"修改页",
        path:'/admin/change',
      }
    ]
  },
  {
    key:3,
    title:'表单页',
    icon:'sheet',
    path:'/admin/echart'
  },
  {
    key:'ban',
    title:'轮播图',
    icon:'banner',
    path:'/admin/banner'
  },
  {
    key:'picList',
    title:'客样照',
    icon:'banner',
    path:'/admin/picList'
  },
  {
    key:4,
    title:'摄影师',
    icon:'Ding',
    path:'/admin/php'
  },
  {
    key:'user',
    title:'用户',
    icon:'user',
    path:"/admin/user",
    children:[
      {
      key:'user-how',
      title:'用户评价',
      path:'/admin/user/how'
      },
      {
        key:'user-book',
        title:"用户预约页",
        path:'/admin/user/book',
      }
    ]
  }
]